### ISSUE TITLE
vagrant sudo

### ISSUE THREAD

**Issue by bbaassssiiee** [ansiblejunky/packer-rhel#1]
https://github.com/ansiblejunky/packer-rhel/blob/37b0af771ec65facacad8339b26152d8adeeba50/http/ks8.cfg#L164

Suggestion: instead of the group %vagrant, configure only the user vagrant:

```sh
echo "vagrant ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/vagrant
```

**Comment by ansiblejunky** [comment]
Agree, thanks! I fixed it.
